---
# file: roles/common/tasks/main.yml
- name: set variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: "Docker | Install for Euler or Centos"
  block:
    - name: Docker | Install dependencies for {{ ansible_distribution }}
      yum:
        name: [ 'yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present
      register: euler_yum_result
      until: euler_yum_result is success
      retries: 1
      delay: 2
    - name: yum repo config
      yum_repository:
        name: "{{repo.name}}"
        description: "{{repo.description}}"
        baseurl: "{{repo.baseurl}}"
        gpgcheck: "{{repo.gpgcheck}}"
        gpgkey: "{{repo.gpgkey}}"

    - name: update yum cache
      yum:
        update_cache: yes
        validate_certs: no

    - name: yum install docker
      yum:
        name: [ ' docker ']
        state: present
      register: euler_yum_docker_result
      until: euler_yum_docker_result is success
      retries: 1
      delay: 2
  when:
    - ansible_distribution in ['CentOS','EulerOS']

- name: "Docker | Install for ubuntu"
  block:
    - name: Docker | Install dependencies for ubuntu,debian
      yum:
        name: [ 'yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present
      register: euler_yum_result
      until: euler_yum_result is success
      retries: 1
      delay: 2
  when: ansible_distribution in ['Ubuntu','Debian']
