---
name: Lint
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 2 * * 0"
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - run: echo ${{ steps.yaml-lint.outputs.logfile }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}
  
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result | ansible-files | lint job
          to: mustafaerbay365@gmail.com
          from: Hello This is Github Action
          body: Build job of ${{github.repository}} completed successfully!
          ignore_cert: true
    
